#!/usr/bin/env python3
"""Check the SMPTE RP 219 pattern against the published values.

The RTL tables are generated by scripts/gen_yuv_palettes.py and the model
reads the same generator, so a sim <-> model match cannot catch a wrong
colour or a wrong layout: both would be wrong together. This script checks
the model against literals typed in from SMPTE RP 219-1 instead:

  1. The palette of the RP 219 target build (YUV, BT.709, limited range)
     reproduces the published 10-bit codes of every chart colour exactly,
     and the 12-bit -I and +Q anchors.
  2. At 1920x1080, 1280x720 and 3840x2160, with the register values the
     host formulas give (smpte_host_geometry), each row band and each
     segment has the right colour, the four row heights are 7/12, 1/12,
     1/12 and 3/12, and both column layouts end where the side panel
     begins.
  3. The Y ramp runs from black exactly to white, rising monotonically,
     with neutral chroma.

The geometry is c = round(3W/28) for every bar, so at 1920 the bars are all
206 pixels and the side panels 239, where RP 219's table alternates 205/206
bars around 240-pixel panels. The check therefore asserts the structure, not
RP 219's per-pixel table.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from vtpgz_model import (  # noqa: E402
    MODE_YUV, YUV_BT709, YUV_LIMITED, PAT_SMPTE, VtpgzConfig,
    _smpte_pixel, smpte_geometry, smpte_host_geometry, smpte_palette,
)
from gen_yuv_palettes import SMPTE_COLORS  # noqa: E402  (path set by the model)

failures: list[str] = []


def fail(msg: str) -> None:
    failures.append(msg)
    print(f"FAIL: {msg}")


# SMPTE RP 219-1, BT.709 Y'CbCr, 10-bit limited range.
RP219_10 = {
    "gray40":    (414, 512, 512),
    "white75":   (721, 512, 512),
    "yellow75":  (674, 176, 543),
    "cyan75":    (581, 589, 176),
    "green75":   (534, 253, 207),
    "magenta75": (251, 771, 817),
    "red75":     (204, 435, 848),
    "blue75":    (111, 848, 481),
    "cyan100":   (754, 615, 64),
    "minus_i":   (244, 612, 395),
    "blue100":   (127, 960, 471),
    "yellow100": (877, 64, 553),
    "plus_q":    (141, 697, 606),
    "white100":  (940, 512, 512),
    "red100":    (250, 409, 960),
    "black":     (64, 512, 512),
    "gray15":    (195, 512, 512),
    "pluge_m2":  (46, 512, 512),
    "pluge_p2":  (82, 512, 512),
    "pluge_p4":  (99, 512, 512),
}
RP219_12 = {
    "minus_i": (976, 2448, 1580),
    "plus_q":  (564, 2787, 2425),
}
# Palette index order (gen_yuv_palettes.SMPTE_COLORS).
ORDER = list(RP219_10)

# The chart, left to right per row band.
LAYOUT = [
    ["gray40", "white75", "yellow75", "cyan75", "green75", "magenta75",
     "red75", "blue75", "gray40"],
    ["cyan100", "minus_i"] + ["white75"] * 6 + ["blue100"],
    ["yellow100", "plus_q"] + ["RAMP"] * 5 + ["white100", "red100"],
    ["gray15", "black", "white100", "black", "pluge_m2", "black", "pluge_p2",
     "black", "pluge_p4", "black", "gray15"],
]


def target_cfg(w: int, h: int, bpc: int) -> VtpgzConfig:
    return VtpgzConfig(width=w, height=h, pattern=PAT_SMPTE,
                       output_mode=MODE_YUV, yuv_matrix=YUV_BT709,
                       yuv_range=YUV_LIMITED, bpc=bpc,
                       **smpte_host_geometry(w, h))


def check_palette() -> None:
    names = [n for n, _ in SMPTE_COLORS]
    if names != ORDER:
        fail(f"generator colour order {names} != {ORDER}")
        return
    for bits, table in ((10, RP219_10), (12, RP219_12)):
        pal = smpte_palette(MODE_YUV, YUV_BT709, YUV_LIMITED, bits)
        for name, want in table.items():
            got = tuple(v >> (12 - bits) for v in pal[ORDER.index(name)])
            if got != want:
                fail(f"{bits}-bit {name}: got {got}, RP 219 is {want}")


def check_layout(w: int = 1920, h: int = 1080) -> None:
    cfg = target_cfg(w, h, 10)
    geo = smpte_geometry(cfg)
    pal = smpte_palette(MODE_YUV, YUV_BT709, YUV_LIMITED, 10)
    unit = h // 12
    if geo["rows"] != [7 * unit, 8 * unit, 9 * unit]:
        fail(f"{w}x{h} row boundaries {geo['rows']}, want 7/8/9 x {unit}")
    if geo["a"][-1] != geo["b"][-1]:
        fail(f"{w}x{h} layouts end at {geo['a'][-1]} (A) and "
             f"{geo['b'][-1]} (B)")
    if abs((w - geo["a"][-1]) - geo["a"][0]) > 1:
        fail(f"{w}x{h} side panels {geo['a'][0]} and {w - geo['a'][-1]} "
             "differ by more than 1")
    ys = [geo["rows"][0] // 2, geo["rows"][0], geo["rows"][1],
          (geo["rows"][2] + h) // 2]
    for row, (y, names) in enumerate(zip(ys, LAYOUT)):
        edges = [0] + geo["b" if row == 3 else "a"] + [w]
        for seg, name in enumerate(names):
            x = (edges[seg] + edges[seg + 1]) // 2
            got = tuple(v >> 2 for v in _smpte_pixel(cfg, x, y))
            if name == "RAMP":
                continue
            want = tuple(v >> 2 for v in pal[ORDER.index(name)])
            if got != want:
                fail(f"{w}x{h} row {row} segment {seg} at x={x}: got {got}, "
                     f"want {name} {want}")


def check_ramp(w: int = 1920, h: int = 1080) -> None:
    cfg = target_cfg(w, h, 10)
    geo = smpte_geometry(cfg)
    y = geo["rows"][1]
    x0, x1 = geo["ramp_x"], geo["a"][6]
    ramp = [tuple(v >> 2 for v in _smpte_pixel(cfg, x, y))
            for x in range(x0, x1)]
    ys = [p[0] for p in ramp]
    if ys[0] != 64:
        fail(f"ramp starts at Y={ys[0]}, want black 64")
    if ys[-1] != 940:
        fail(f"ramp ends at Y={ys[-1]}, want white 940")
    if any(b < a for a, b in zip(ys, ys[1:])):
        fail("ramp is not monotonic")
    if any(p[1:] != (512, 512) for p in ramp):
        fail("ramp chroma is not neutral")
    # The pixel either side of the ramp is +Q and 100% white.
    pal = smpte_palette(MODE_YUV, YUV_BT709, YUV_LIMITED, 10)
    for x, name in ((x0 - 1, "plus_q"), (x1, "white100")):
        got = tuple(v >> 2 for v in _smpte_pixel(cfg, x, y))
        want = tuple(v >> 2 for v in pal[ORDER.index(name)])
        if got != want:
            fail(f"x={x} next to the ramp: got {got}, want {name} {want}")


def main() -> int:
    check_palette()
    for w, h in ((1920, 1080), (1280, 720), (3840, 2160)):
        check_layout(w, h)
        check_ramp(w, h)
    if failures:
        print(f"\n{len(failures)} failure(s)")
        return 1
    print("PASS: SMPTE RP 219 palette matches the published 10/12-bit codes; "
          "layout and ramp correct at 1920x1080, 1280x720, 3840x2160")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
