#!/usr/bin/env python3
"""
load.py -- Load and run the vtpgZero KV260 DP demo via JTAG using Xilinx XSCT.

Author: Leonardo Capossio - bard0 design - hello@bard0.com
Year:   2026

Tool resolution: `xsct` on PATH or the $XSCT env var.

Modes:
  default  -- assume PMUFW + FSBL are already running, just dow + con.
  --cold   -- full cold-boot cycle: set JTAG boot mode, load PMUFW + FSBL,
              then dow + con this app. Required after every power cycle, AND
              required between successive `load.py` invocations because each
              `dow` leaves A53 in a state where the next one silently fails.

For cold boot, provide PMUFW/FSBL explicitly via $KV260_PMUFW_ELF and
$KV260_FSBL_ELF, or set $KV260_BSP_DIR to the BSP generated by build_bsp.py.
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

KV_DIR = Path(__file__).resolve().parents[1]

TARGETS = {
    "box": KV_DIR / "build" / "dp_vtpgzero_box.elf",
}

def resolve_xsct() -> str:
    for cand in ("xsct", "xsct.bat"):
        p = shutil.which(cand)
        if p:
            return p
    p = os.environ.get("XSCT")
    if p and Path(p).exists():
        return p
    sys.exit("ERROR: 'xsct' not in PATH and $XSCT is not set.")


def run_xsct(xsct: str, tcl_path: Path) -> int:
    if xsct.lower().endswith(".bat"):
        return subprocess.call(["cmd", "/c", xsct, str(tcl_path)])
    return subprocess.call([xsct, str(tcl_path)])


def find_default_bitstream() -> str | None:
    # Preferred location if build_pl.py was taught to stage the bitstream.
    direct = KV_DIR / "build" / "pl" / "vtpgzero_kv260.bit"
    if direct.is_file():
        return str(direct)

    # Current flow exports the bitstream inside the BSP/platform workspace
    # because the XSA is written with -include_bit and Vitis extracts it to
    # hw/vtpgzero_kv260.bit during platform generation.
    exported = KV_DIR / "build" / "bsp_vtpgzero_kv260" / "hw_platform" / "hw" / "vtpgzero_kv260.bit"
    if exported.is_file():
        return str(exported)

    # Fallback for similarly named BSP workspaces.
    for cand in sorted(KV_DIR.glob("build/bsp_*/hw_platform/hw/vtpgzero_kv260.bit")):
        if cand.is_file():
            return str(cand)
    return None


COLD_BOOT_TCL = """\
connect

# 0. Override boot mode to JTAG (in case the board is set to SD/QSPI).
targets -set -filter {{name =~ "PSU"}}
mwr 0xffca0010 0x0
mwr 0xff5e0200 0x0100
rst -system
after 1000

# 1. Security gates
targets -set -nocase -filter {{name =~ "*PSU*"}}
mwr 0xFFCA0038 0x1FF
after 500

# 2. PMU firmware
targets -set -nocase -filter {{name =~ "*MicroBlaze PMU*"}}
catch {{stop}}
after 200
dow {pmufw}
con
after 3000

# 3. RVBAR + FSBL
targets -set -nocase -filter {{name =~ "*A53*#0"}}
rst -processor -clear-registers
after 1000
targets -set -nocase -filter {{name =~ "*PSU*"}}
mwr 0xFD5C0040 0xFFFC0000
mwr 0xFD5C0044 0x00000000
after 100

targets -set -nocase -filter {{name =~ "*A53*#0"}}
dow {fsbl}
after 500
con
after 20000
catch {{stop}}
after 500
{bit_section}
puts "=== cold boot done ==="
"""

BIT_PROGRAM_TCL = """\
puts "Programming PL bitstream..."
targets -set -nocase -filter {{name =~ "*PSU*"}}
# When multiple FPGA devices are enumerated (xsdb sees both the SoC PL and
# something else), fpga -f errors out. Select the first PL target explicitly.
targets 2
fpga -f {bit}
after 2000
targets -set -nocase -filter {{name =~ "*PSU*"}}
# Verify PL is up by reading PCAP_STATUS bit 11 (PL_DONE).
# Address: 0xFFCA3010, bit 11 = INIT_B/EOS done.
set pcap [mrd -force -value 0xFFCA3010]
puts "PCAP_STATUS = $pcap"
if {{($pcap & 0x800) == 0}} {{
    puts "ERROR: PL_DONE bit not set after fpga -f"
    exit 1
}}
puts "PL programmed (DONE asserted)"

# --- PS-PL isolation removal + fabric reset toggle ---
# In a JTAG flow the FSBL never calls psu_ps_pl_isolation_removal_data()
# or psu_ps_pl_reset_config_data() because it doesn't load a bitstream
# itself. We must do it here so that:
#   1. AXI transactions from PS HPM0_FPD reach the PL fabric.
#   2. proc_sys_reset in the BD sees the pl_resetn0 edge and releases
#      peripheral_aresetn.
# See docs/PS_PL_ISOLATION.md.

# 1. Remove PS-PL isolation (PL power-up request to PMU)
mwr -force 0xFFD80118 [expr {{[mrd -force -value 0xFFD80118] | 0x00800000}}]
mwr -force 0xFFD80120 [expr {{[mrd -force -value 0xFFD80120] | 0x00800000}}]
after 100

# 2. Toggle pl_resetn0 via EMIO GPIO bank5 bit31
mwr -force 0xFF0A002C 0x80000000
mwr -force 0xFF0A0344 0x80000000
mwr -force 0xFF0A0348 0x80000000
mwr -force 0xFF0A0054 0x80000000
after 50
mwr -force 0xFF0A0054 0x00000000
after 50
mwr -force 0xFF0A0054 0x80000000
after 200
puts "PL isolation removed + fabric reset toggled"
"""

LOAD_TCL = """\
connect
targets -set -filter {{name =~ "Cortex-A53 #0"}}
rst -processor -clear-registers
dow {elf}
con
puts "vtpgZero KV260 demo running. UART output on KV260 USB-UART (FT4232H ch.B) @ 115200."
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", choices=sorted(TARGETS.keys()), default="box",
                    help="Which app to load (default: box)")
    ap.add_argument("--cold", action="store_true",
                    help="Full cold boot: JTAG mode + PMUFW+FSBL + load app.")
    ap.add_argument("--bit", default=None,
                    help="PL bitstream (.bit) to program after FSBL. Required "
                         "for the 'box' target. Defaults to "
                         "$KV260_BITSTREAM or hw/kv260/build/pl/vtpgzero_kv260.bit.")
    args = ap.parse_args()
    elf = TARGETS[args.target]
    bit = args.bit
    if bit is None:
        env_bit = os.environ.get("KV260_BITSTREAM")
        if env_bit:
            bit = env_bit
        else:
            bit = find_default_bitstream()
    if args.target == "box" and not bit:
        sys.exit("ERROR: --target box requires a PL bitstream. Pass --bit, "
                 "set $KV260_BITSTREAM, or build it via hw/kv260/scripts/build_pl.py.")

    if not elf.is_file():
        sys.exit(f"ERROR: {elf} not found. "
                 f"Run hw/kv260/scripts/build.py --target {args.target} first.")
    xsct = resolve_xsct()

    if args.cold:
        # Cold-boot needs PMUFW + FSBL elfs that match the XSA (and therefore
        # the BSP we link the app against). Order of precedence:
        #   1. $KV260_PMUFW_ELF + $KV260_FSBL_ELF (explicit override)
        #   2. $KV260_BSP_DIR/zynqmp_pmufw/pmufw.elf + zynqmp_fsbl/fsbl_a53.elf
        #      (Vitis platform-generate output -- see scripts/build_bsp.py)
        pmufw = os.environ.get("KV260_PMUFW_ELF")
        fsbl = os.environ.get("KV260_FSBL_ELF")
        if not (pmufw and fsbl):
            bsp = os.environ.get("KV260_BSP_DIR")
            if bsp:
                bsp_p = Path(bsp).resolve()
                cand_pmufw = bsp_p / "zynqmp_pmufw" / "pmufw.elf"
                cand_fsbl = bsp_p / "zynqmp_fsbl" / "fsbl_a53.elf"
                if cand_pmufw.is_file() and cand_fsbl.is_file():
                    pmufw, fsbl = str(cand_pmufw), str(cand_fsbl)

        if pmufw and fsbl:
            print(f"[load] cold: PMUFW = {pmufw}")
            print(f"[load] cold: FSBL  = {fsbl}")
            bit_section = ""
            if bit:
                print(f"[load] cold: BIT   = {bit}")
                bit_section = BIT_PROGRAM_TCL.format(bit=Path(bit).as_posix())
            cold_tcl = COLD_BOOT_TCL.format(
                pmufw=Path(pmufw).as_posix(),
                fsbl=Path(fsbl).as_posix(),
                bit_section=bit_section)
            with tempfile.NamedTemporaryFile("w", suffix=".tcl",
                                             delete=False) as f:
                f.write(cold_tcl)
                cold_path = Path(f.name)
            try:
                rc = run_xsct(xsct, cold_path)
            finally:
                cold_path.unlink(missing_ok=True)
            if rc:
                return rc
        else:
            sys.exit("ERROR: --cold needs PMUFW/FSBL. Provide "
                     "$KV260_PMUFW_ELF + $KV260_FSBL_ELF, or set "
                     "$KV260_BSP_DIR to the BSP built by "
                     "hw/kv260/scripts/build_bsp.py.")

    with tempfile.NamedTemporaryFile("w", suffix=".tcl", delete=False) as f:
        f.write(LOAD_TCL.format(elf=elf.as_posix()))
        tcl = Path(f.name)
    try:
        print(f"[load] xsct {tcl}")
        return run_xsct(xsct, tcl)
    finally:
        tcl.unlink(missing_ok=True)


if __name__ == "__main__":
    sys.exit(main())
